version: "3.8"

services:  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    container_name: a_elasticsearch    
    restart: always
    environment:
      discovery.type: "single-node"
    ports:
      - 9200:9200
    expose:
      - "9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - movie_proj    
  
  redis:
    image: redis:6.2.6
    container_name: a_redis
    restart: always      
    ports:
      - 6379:6379
    expose:
      - "6379"
    command:
      - redis-server   
    volumes:
      - redis-data:/data 
    networks:
      - movie_proj

  main:    
    container_name: a_main-app
    build: 
      context: .
      dockerfile: dockerfile
    networks:
      - movie_proj
    ports:
      - 8000:8000
    depends_on:
      - elasticsearch
      - redis

networks:
  movie_proj:
    external: true
  default:

volumes:
  elasticsearch-data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/elasticsearch-data
      o: bind

  redis-data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/redis-data
      o: bind
  