version: "3.8"

services:  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    container_name: a_elasticsearch        
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms128m -Xmx128m"
      - discovery.type=single-node
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1         
    expose:
      - "9200"
    volumes:
      - ${PWD}/elasticsearch-data:/usr/share/elasticsearch/data
  
  redis:
    image: redis:6.2.6
    container_name: a_redis        
    expose:
      - "6379"
    command:
      - redis-server   
    volumes:
      - ${PWD}/redis-data:/data

  main:    
    container_name: a_main-app
    build: 
      context: .
      dockerfile: dockerfile-main 
    env_file:
      - .env
    depends_on:
      - elasticsearch
      - redis
  
  nginx:
    build: 
      context: .
      dockerfile: dockerfile-nginx    
    volumes:
      - ./nginx:/etc/nginx
      - ./nginx/conf.d:/etc/nginx/conf.d            
    depends_on:
      - main
    ports:
      - "80:80"
  