FROM python:3.9

ENV PYTHONUNBUFFERED 1

WORKDIR /code

COPY ./src/requirements.txt /code/requirements.txt

RUN pip install --upgrade pip && \
    pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY ./src /code

ENV PYTHONPATH "${PYTHONPATH}:/code"