FROM python:3.9

WORKDIR /code

COPY ./requirements.txt /code/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY ./ /code

# ENTRYPOINT [ "python", "utils/wait_for_es.py", "&&", \
#             "python", "utils/wait_for_redis.py" ]

# CMD ["pytest", "tests/functional/src/test_filmworks.py"]