name: we-make-linter-check

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - uses: actions/checkout@v2
      - name: make-linter-report-directory
        run: |
          mkdir -p lint_report/src/api/wemake-python-styleguide/
      - name: install-dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wemake-python-styleguide flake8-html
      - name: lint-codestyle
        run: |
          flake8 src/api --exit-zero --format=html --htmldir=lint_report/src/api/wemake-python-styleguide/
      - name: load-report
        uses: actions/upload-artifact@v3.1.0
        with:
          name: lint_report
          path: lint_report/
