name: we-make-linter-check

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: wemake-python-styleguide
      uses: wemake-services/wemake-python-styleguide
